### ISSUE TITLE
way to overwrite/delete/list db keys?

### ISSUE THREAD

**Issue by zbeekman** [technoweenie/guillotine#20]
Is there anyway to overwrite, list, or delete keys via GET or POST? I'm guessing not since you don't support authentication but I thought I'd check anyway. (Disclaimer: I have no background in ruby or web stuff) It would be great not to have to fire up a redis cli and poke around that way.

**Comment by technoweenie** [comment]
Yes for [deleting keys](https://github.com/technoweenie/guillotine/blob/master/lib/guillotine/adapters/redis_adapter.rb#L51-L76), but not for listing keys. There are adapters for a variety of systems, with their own behaviors and drawbacks when listing keys. If you're thinking about this, I'd highly recommend going with the activerecord or sequel adapters, and using postgres or mysql. git.io currently runs on Heroku with Postgres. It handles the volume of data just fine, and of course postgres has great query capabilities.

Also keep in mind that this library is not under active development, unfortunately. You're of course welcome to use/fork the library, but don't count on an active community to answer questions or fix bugs.

**Comment by zbeekman** [comment]
awesome thanks for your help!
