### ISSUE TITLE
Inverse transform

### ISSUE THREAD

**Issue by valtih1978** [technoweenie/guillotine#21]
I entered `https://git.io/vo4w5` into [git.io](http://git.io) and wanted to know where it comes from. Obviously, conversion failed because it makes no sense to compress the compressed file. But, you can uncompress it if compressed supplied, and show what the original URL used to be, right? Simply endtering url into the browser's window is not an option because it will download the file, which may be not what you want.

This concerns the web interface, not command line. I see that [in the command line](https://github.com/blog/985-git-io-github-url-shortener) you can see the redirect link.

**Comment by technoweenie** [comment]
Git.io and the web interface is not part of this project. It doesn't have a way to show the link for a shortcut.
